DROP TABLE IF EXISTS `ps_smart_blog_category_lang`;
CREATE TABLE `ps_smart_blog_category_lang` (
  `id_smart_blog_category` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL DEFAULT '0',
  `meta_title` varchar(150) DEFAULT NULL,
  `meta_keyword` varchar(200) DEFAULT NULL,
  `meta_description` varchar(350) DEFAULT NULL,
  `description` varchar(10000) DEFAULT NULL,
  `link_rewrite` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id_smart_blog_category`,`id_lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Scheme for table ps_smart_blog_category_lang */
INSERT INTO `ps_smart_blog_category_lang` VALUES
('1','1','Ullamcorper erat',NULL,NULL,'<p><strong>Vivamus vitae laoreet erat</strong>, eget egestas est. Donec at auctor arcu, at suscipit orci. Quisque vel risus odio. In porttitor, neque et cursus interdum, lacus felis scelerisque risus, id euismod sapien lorem et tortor. Curabitur augue sem, lobortis vitae sapien sit amet, tempus posuere sapien. Aenean ut felis a orci volutpat maximus quis lobortis sem. <span style=\"text-decoration: line-through;\">Cum sociis natoque penatibus et magnis</span> dis parturient montes, nascetur ridiculus mus. Sed felis tortor, tempor ut mattis a, commodo at diam. Nullam nunc lorem, ornare id magna vitae, lobortis lacinia magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris in aliquet sem, sit amet placerat erat. Maecenas non tellus rutrum, eleifend diam eget, eleifend massa. Donec luctus sapien justo, <span style=\"text-decoration: underline;\"><em>eget tincidunt tellus molestie ut</em></span>. Mauris in pharetra eros, eu hendrerit tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>','ullamcorper-erat'),
('1','2','Ullamcorper erat',NULL,NULL,'<p><strong>Vivamus vitae laoreet erat</strong>, eget egestas est. Donec at auctor arcu, at suscipit orci. Quisque vel risus odio. In porttitor, neque et cursus interdum, lacus felis scelerisque risus, id euismod sapien lorem et tortor. Curabitur augue sem, lobortis vitae sapien sit amet, tempus posuere sapien. Aenean ut felis a orci volutpat maximus quis lobortis sem. <span style=\"text-decoration: line-through;\">Cum sociis natoque penatibus et magnis</span> dis parturient montes, nascetur ridiculus mus. Sed felis tortor, tempor ut mattis a, commodo at diam. Nullam nunc lorem, ornare id magna vitae, lobortis lacinia magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris in aliquet sem, sit amet placerat erat. Maecenas non tellus rutrum, eleifend diam eget, eleifend massa. Donec luctus sapien justo, <span style=\"text-decoration: underline;\"><em>eget tincidunt tellus molestie ut</em></span>. Mauris in pharetra eros, eu hendrerit tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>','ullamcorper-erat'),
('1','3','Ullamcorper erat',NULL,NULL,'<p><strong>Vivamus vitae laoreet erat</strong>, eget egestas est. Donec at auctor arcu, at suscipit orci. Quisque vel risus odio. In porttitor, neque et cursus interdum, lacus felis scelerisque risus, id euismod sapien lorem et tortor. Curabitur augue sem, lobortis vitae sapien sit amet, tempus posuere sapien. Aenean ut felis a orci volutpat maximus quis lobortis sem. <span style=\"text-decoration: line-through;\">Cum sociis natoque penatibus et magnis</span> dis parturient montes, nascetur ridiculus mus. Sed felis tortor, tempor ut mattis a, commodo at diam. Nullam nunc lorem, ornare id magna vitae, lobortis lacinia magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris in aliquet sem, sit amet placerat erat. Maecenas non tellus rutrum, eleifend diam eget, eleifend massa. Donec luctus sapien justo, <span style=\"text-decoration: underline;\"><em>eget tincidunt tellus molestie ut</em></span>. Mauris in pharetra eros, eu hendrerit tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>','ullamcorper-erat'),
('1','4','Ullamcorper erat',NULL,NULL,'<p><strong>Vivamus vitae laoreet erat</strong>, eget egestas est. Donec at auctor arcu, at suscipit orci. Quisque vel risus odio. In porttitor, neque et cursus interdum, lacus felis scelerisque risus, id euismod sapien lorem et tortor. Curabitur augue sem, lobortis vitae sapien sit amet, tempus posuere sapien. Aenean ut felis a orci volutpat maximus quis lobortis sem. <span style=\"text-decoration: line-through;\">Cum sociis natoque penatibus et magnis</span> dis parturient montes, nascetur ridiculus mus. Sed felis tortor, tempor ut mattis a, commodo at diam. Nullam nunc lorem, ornare id magna vitae, lobortis lacinia magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris in aliquet sem, sit amet placerat erat. Maecenas non tellus rutrum, eleifend diam eget, eleifend massa. Donec luctus sapien justo, <span style=\"text-decoration: underline;\"><em>eget tincidunt tellus molestie ut</em></span>. Mauris in pharetra eros, eu hendrerit tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>','ullamcorper-erat'),
('1','5','Ullamcorper erat',NULL,NULL,'<p><strong>Vivamus vitae laoreet erat</strong>, eget egestas est. Donec at auctor arcu, at suscipit orci. Quisque vel risus odio. In porttitor, neque et cursus interdum, lacus felis scelerisque risus, id euismod sapien lorem et tortor. Curabitur augue sem, lobortis vitae sapien sit amet, tempus posuere sapien. Aenean ut felis a orci volutpat maximus quis lobortis sem. <span style=\"text-decoration: line-through;\">Cum sociis natoque penatibus et magnis</span> dis parturient montes, nascetur ridiculus mus. Sed felis tortor, tempor ut mattis a, commodo at diam. Nullam nunc lorem, ornare id magna vitae, lobortis lacinia magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris in aliquet sem, sit amet placerat erat. Maecenas non tellus rutrum, eleifend diam eget, eleifend massa. Donec luctus sapien justo, <span style=\"text-decoration: underline;\"><em>eget tincidunt tellus molestie ut</em></span>. Mauris in pharetra eros, eu hendrerit tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>','ullamcorper-erat');
